# syntax=docker/dockerfile:1.7
#
# Multi-stage build for retro-controlpanel-card. Targets:
#   - build      : produces /app/dist/retro-controlpanel-card.js
#   - test       : runs vitest unit tests (fails the build if they fail)
#   - test-ui    : runs Playwright UI tests against the built bundle
#   - export     : empty scratch image that contains only /dist - use with
#                  `--output type=local,dest=./dist` to extract the bundle.

# ---------- deps: install node_modules (cached unless package.json changes) ----------
# Alpine + current Node LTS: far smaller package set than Debian, so far fewer
# OS CVEs. This is a build-only image - the shipped artifact is a plain JS file
# (see the `export` stage), so nothing from here is deployed.
FROM node:22-alpine AS deps
WORKDIR /app
# Don't pull Playwright browsers during install: they're glibc builds that
# wouldn't run on Alpine, and they go unused anyway - the test-ui stage gets
# its browsers from the Playwright base image, not from node_modules.
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
COPY package.json ./
# package-lock.json may not exist on the first build; the wildcard makes the
# COPY a no-op rather than an error if it's missing.
COPY package-lock.json* ./
RUN --mount=type=cache,target=/root/.npm \
    npm install --no-audit --no-fund

# ---------- build: produce dist/retro-controlpanel-card.js ----------
FROM deps AS build
COPY tsconfig.json rollup.config.mjs ./
COPY src ./src
RUN npm run build

# ---------- test: unit tests (vitest) ----------
# The RUN deliberately never fails: it captures vitest's real exit code into
# reports/exitcode so the report can be extracted even when tests fail (a
# failing RUN would abort the build before any export stage). build.ps1 reads
# reports/exitcode and surfaces the pass/fail.
FROM build AS test
COPY vitest.config.ts ./
COPY tools ./tools
COPY tests/unit ./tests/unit
# Run tests (junit + json), then render a self-contained HTML report from the
# json. The HTML generation is best-effort (|| true) and the captured exit
# code is vitest's, so a failing run still produces the report.
RUN mkdir -p reports && sh -c 'npm run test:report; code=$?; npm run report:html || true; echo $code > reports/exitcode'

# ---------- test-report: vitest reports (junit + exitcode) ----------
#   docker build --target test-report --output type=local,dest=./reports/unit .
FROM scratch AS test-report
COPY --from=test /app/reports /

# ---------- test-ui: Playwright UI tests ----------
# Uses Microsoft's Playwright base image so chromium is already installed at
# the matching version. We import node_modules + the built dist from the
# earlier stages instead of rebuilding from scratch.
#
# IMPORTANT: this image tag and the @playwright/test version in package.json
# MUST move together - a mismatch means the installed client looks for a
# browser revision the image doesn't ship, and every test fails at launch.
FROM mcr.microsoft.com/playwright:v1.60.0-noble AS test-ui
WORKDIR /app
COPY --from=deps  /app/node_modules ./node_modules
COPY --from=build /app/dist         ./dist
COPY package.json playwright.config.ts ./
COPY src ./src
COPY tests ./tests
# Same pattern as the unit-test stage: never fail the build, capture the real
# exit code so the HTML/JUnit reports can be extracted even on failure.
RUN mkdir -p reports && sh -c 'npm run test:ui; echo $? > reports/exitcode'

# ---------- test-ui-report: Playwright reports (html + junit + traces + exitcode) ----------
#   docker build --target test-ui-report --output type=local,dest=./reports/ui .
FROM scratch AS test-ui-report
COPY --from=test-ui /app/reports /

# ---------- screenshots: theme PNGs generated by card.screenshots.spec.ts ----------
# Build with:
#   docker build --target screenshots --output type=local,dest=./docs .
# to refresh docs/<theme>.png used in the README.
FROM scratch AS screenshots
COPY --from=test-ui /app/screenshots /

# ---------- export: the default target; just the built bundle as an image ----------
# Build with:
#   docker build --target export --output type=local,dest=./dist .
# and the bundle lands on your host filesystem - no bind mounts needed.
FROM scratch AS export
COPY --from=build /app/dist /
